import { test } from "node:test";
import assert from "node:assert/strict";
import { loadPage } from "./helpers/dom.mjs";

const PAGES = ["index.html", "products.html", "about.html", "client.html", "contact.html"];

test("every page parses into a document with a <title>", () => {
  for (const name of PAGES) {
    const { dom } = loadPage(name);
    const title = dom.window.document.querySelector("title");
    assert.ok(title, `${name} is missing a <title>`);
    assert.ok(title.textContent.trim().length > 0, `${name} has an empty <title>`);
  }
});

test("every page loads the shared behaviour script and stylesheet", () => {
  for (const name of PAGES) {
    const { html } = loadPage(name);
    assert.ok(html.includes("js/tucklers.js"), `${name} does not include js/tucklers.js`);
  }
});

test("every page carries a persistent cart badge and mobile side nav", () => {
  for (const name of PAGES) {
    const { dom } = loadPage(name);
    const doc = dom.window.document;
    assert.ok(doc.getElementById("cart-badge"), `${name} is missing #cart-badge`);
    assert.ok(doc.getElementById("mySidenav"), `${name} is missing #mySidenav`);
  }
});

test("the products page wires the filter + search UI the script expects", () => {
  const { dom } = loadPage("products.html");
  const doc = dom.window.document;
  assert.ok(doc.getElementById("shop-grid"), "missing #shop-grid");
  assert.ok(doc.getElementById("shop-search"), "missing #shop-search");
  assert.ok(doc.getElementById("no-results"), "missing #no-results");

  const pills = doc.querySelectorAll(".filter-pill");
  assert.ok(pills.length >= 2, "expected multiple filter pills");
  // Exactly one pill starts active, and it is the "all" pill.
  const active = [...pills].filter((p) => p.classList.contains("active"));
  assert.equal(active.length, 1);
  assert.equal(active[0].getAttribute("data-filter"), "all");

  // Every product card exposes the data hooks the filter reads.
  const cards = doc.querySelectorAll("#shop-grid [data-cat]");
  assert.ok(cards.length > 0, "no product cards found");
  for (const card of cards) {
    assert.ok(card.getAttribute("data-cat"), "a product card is missing data-cat");
    assert.ok(card.getAttribute("data-name"), "a product card is missing data-name");
  }

  // Each category referenced by a pill (except "all") maps to a real card.
  const cats = new Set([...cards].map((c) => c.getAttribute("data-cat")));
  for (const pill of pills) {
    const f = pill.getAttribute("data-filter");
    if (f !== "all") {
      assert.ok(cats.has(f), `filter "${f}" has no matching product`);
    }
  }
});

test("every Add to Bag button labels itself with a product name", () => {
  const { dom } = loadPage("products.html");
  const buttons = dom.window.document.querySelectorAll(".add-bag");
  assert.ok(buttons.length > 0, "no add-bag buttons found");
  for (const btn of buttons) {
    assert.ok(btn.getAttribute("data-name"), "an add-bag button is missing data-name");
  }
});

test("the contact page exposes the ids and required fields the validator needs", () => {
  const { dom } = loadPage("contact.html");
  const doc = dom.window.document;
  assert.ok(doc.getElementById("contact-form"), "missing #contact-form");
  assert.ok(doc.getElementById("form-status"), "missing #form-status");
  const required = doc.querySelectorAll("#contact-form [data-required]");
  assert.ok(required.length >= 3, "expected several required fields");
  assert.ok(
    doc.querySelector('#contact-form input[type="email"]'),
    "contact form has no email field"
  );
});

test("the newsletter signup on the home page is wired for capture", () => {
  const { dom } = loadPage("index.html");
  const doc = dom.window.document;
  const form = doc.getElementById("newsletter-form");
  assert.ok(form, "missing #newsletter-form");
  assert.ok(form.querySelector('input[type="email"]'), "newsletter has no email input");
  assert.ok(doc.getElementById("newsletter-note"), "missing #newsletter-note");
});

test("pages ship no third-party builder branding", () => {
  const forbidden = /lovable|lovable\.dev|cursor\.sh|generated by/i;
  for (const name of PAGES) {
    const { html } = loadPage(name);
    assert.doesNotMatch(html, forbidden, `${name} contains builder branding`);
  }
});
